<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDayOfTheWeek(int $dayOfTheWeek)
    {
        $em = $this->getEntityManager();
        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('AppBundle:Answer', 'a');
        $rsm->addFieldResult('a', 'id', 'id');
        $rsm->addFieldResult('a', 'mood', 'mood');

        $query = $em->createNativeQuery('SELECT id, mood FROM answer WHERE DAYOFWEEK(createdAt) = ' .
            $dayOfTheWeek, $rsm);

        return $query->getResult();
    }
}
